### ISSUE TITLE
Self-hosting

### ISSUE THREAD

**Issue by mehrdad1990** [celest-dev/celest#144]
Hi, thank you for the great project. When will self-hosting become available?

**Comment by dnys1** [comment]
Hi @mehrdad1990, we are actively working on the design for a self-hosting mechanism. When we feel confident in our ability to support such a solution, we'll create an RFC to collect feedback.

I expect to have more information for you within the next couple weeks.

**Comment by rubenferreira97** [comment]
I’d like to share my perspective on why a self-host open source solution is beneficial, given my appreciation for business models like SurrealDB and Supabase:

**Greater Flexibility and Control:** When I self-host an open-source solution, I gain the ability to tailor the software to my specific needs without being restricted by the limitations of a proprietary system. This flexibility allows me to modify the code, integrate with other tools, and scale according to my requirements. It's particularly valuable because it ensures that the system evolves in line with my business needs rather than being tied to the roadmap of a third-party vendor. Additionally, I'm not at the mercy of sudden price increases or changes in service offerings from a proprietary provider.

**Reduced Dependency and Risk:** By choosing an open-source, self-hosted solution, I mitigate the risk associated with relying on a single vendor. Proprietary solutions can become a single point of failure—if the company shuts down, changes its business model, or alters its terms of service unfavorably, my operations could be severely impacted. With an open-source, self-hosted model, I have the assurance that I can continue using and maintaining the software independently, ensuring continuity and stability for my business operations.

**Encourages Open Source Contributions:** Using and supporting open-source software fosters a community of collaboration and innovation. By contributing to these projects, I can help improve the software for everyone, share my enhancements with others, and benefit from the collective knowledge and improvements made by the community. This collaborative environment not only drives better software but also empowers users and developers to be part of a larger, supportive ecosystem.

---

**But, I also recognize the need to sustain and grow a business.** To continue providing valuable software, there needs to be a viable revenue model. This is why offering paid cloud solutions makes sense. While users can freely self-host and benefit from the open-source model, those who prefer the convenience, scalability, and support of a managed cloud service can opt for the paid offerings. This balance allows for a sustainable business model while still promoting openness and community contributions.

**Comment by dnys1** [comment]
Thanks for the feedback, @rubenferreira97! Your points are valid and heard 🙂

**Comment by ps6067966** [comment]
+1

**Comment by TobiasHeidingsfeld** [comment]
Any update on this?

**Comment by dnys1** [comment]
Celest v1 has been released with a new `celest build` command that will bundle your backend and its dependencies into a Docker container that you can host anywhere!

Give it a try and let us know what you think 🚀  https://celest.dev/docs/download

We're committed to supporting the full set of features offered by Celest in self-hosted environments so please do file issues and feedback for anything that's missing.

**Comment by mehrdad1990** [comment]
@dnys1
Great news
